import type { Metadata } from "next";
import { Toaster } from "sonner";
import { SidebarProvider } from "@/components/ui/sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`antialiased`}>
          <SidebarProvider>
            {children}
            <Toaster richColors />
          </SidebarProvider>
      </body>
    </html>
  );
}
